project:
  type: website
  output-dir: docs
  resources:
    - protocols_src/templates/*

website:
  title: "Protocol Library"

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "Overview"
        icon: house

      - section: "Onboarding"
        icon: person-check
        contents:
          - href: protocols_src/onboarding/index.qmd
            text: "Onboarding overview"

          - href: protocols_src/onboarding/checklist.qmd
            text: "Onboarding checklist"

          - href: protocols_src/onboarding/contacts.qmd
            text: "Key contacts"

          - href: protocols_src/onboarding/training/data_and_reproducibility.qmd
            text: "Data and reproducibility"

          - section: "Lab information"
            contents:
              - href: protocols_src/onboarding/lab_info/index.qmd
                text: "Lab information overview"

              - href: protocols_src/onboarding/lab_info/lab_expectations.qmd
                text: "Lab expectations"

              - href: protocols_src/onboarding/lab_info/lab_etiquette.qmd
                text: "Lab etiquette"

              - href: protocols_src/onboarding/lab_info/communication_norms.qmd
                text: "Communication norms"

          - section: "Institute information"
            contents:
              - href: protocols_src/onboarding/institute/index.qmd
                text: "Institute overview"

              - href: protocols_src/onboarding/institute/institute_overview.qmd
                text: "Institute overview page"

              - href: protocols_src/onboarding/institute/research_groups.qmd
                text: "Research groups"

              - href: protocols_src/onboarding/institute/core_facilities.qmd
                text: "Core facilities"

      - href: protocols_src/buffers/index.qmd
        text: "Buffers"
        icon: droplet

      - href: protocols_src/general/index.qmd
        text: "General"
        icon: gear

      - href: protocols_src/human/index.qmd
        text: "Human"
        icon: person

      - href: protocols_src/mouse/index.qmd
        text: "Mouse"
        icon: mouse

      - href: protocols_src/resources/index.qmd
        text: "Resources"
        icon: link-45deg

      - href: protocols_src/templates/index.qmd
        text: "Templates"
        icon: file-earmark-spreadsheet

format:
  html:
    theme: flatly
    math: mathjax
    toc: true
    number-sections: false
    geometry: "margin=2cm"
    fontsize: 11pt
    colorlinks: false
  pdf:
    toc: false
    pdf-engine: xelatex
    number-sections: false
    geometry: "margin=2cm"
    fontsize: 11pt
    colorlinks: false
