project:
  type: website
  output-dir: docs
  resources:
    - templates/*

website:
  title: "Protocol Library"

  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "Overview"
        icon: house

      - href: protocols_src/buffers/index.qmd
        text: "Buffers"
        icon: droplet

      - href: protocols_src/general/index.qmd
        text: "General"
        icon: gear

      - href: protocols_src/human/index.qmd
        text: "Human"
        icon: person

      - href: protocols_src/mouse/index.qmd
        text: "Mouse"
        icon: mouse

      - href: protocols_src/templates/index.qmd
        text: "Templates"
        icon: file-earmark-spreadsheet

format:
  html:
    theme: flatly
    math: mathjax
    toc: true
    number-sections: false
    geometry: "margin=2cm"
    fontsize: 11pt
    colorlinks: false
  pdf:
    toc: false
    pdf-engine: xelatex
    number-sections: false
    geometry: "margin=2cm"
    fontsize: 11pt
    colorlinks: false
